/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <sys/time.h>


void
rpc_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *get_path_1_arg;
	sortElement  *result_2;
	sortElement  get_sort_1_arg;
	char * *result_3;
	char *get_echo_1_arg = malloc(100);
	char * *result_4;
	char *get_check_1_arg = malloc(100);
	matrixMulElements  *result_5;
	matrixMulElements  get_matmul_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PROG, RPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	char choice;

	/*
	*This while loop will only terminate when user will provide 'q' otherwise for 
	*anyother choice it will send request to the server will execute the corresponding
	*functionalities.
	*/
	while (1)
	{
		printf("\nProvide <p, s, e, c, m> or any other to quit:\np. Path \ns. Sort \ne. Echo \nc. Check \nm. Multiplier\nq. Quit\n");

		printf("Choice = ");
		scanf("\n%c", &choice);

		/*
		*If this condition is true then it will request server for the working directory
		*and once receive the response will print the information
		*/
		if (choice == 'p')
		{	struct timeval stop, start;
			gettimeofday(&start, NULL);
			result_1 = get_path_1((void *)&get_path_1_arg, clnt);
			gettimeofday(&stop, NULL);
			printf("Time elapsed (microSec): %lu\n", stop.tv_usec - start.tv_usec);

			printf("\nSERVER RESPONSE > PWD = %s\n", *result_1);
			if (result_1 == (char **)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
		}

		/*
                *If this condition is true then it will send an unsorted array to server
                *array input will be given by the user 
		*Server will return the sorted array to client
                */
		else if (choice == 's')
		{
			int data[100], n, i;
			printf("please provide the array length: ");
			scanf("%d", &get_sort_1_arg.len);
			printf("please provide the array elements:\n");
			for (i = 0; i < get_sort_1_arg.len; i++){
				scanf("%d", &get_sort_1_arg.element[i]);
			}

			struct timeval stop, start;
			gettimeofday(&start, NULL);
			result_2 = get_sort_1(&get_sort_1_arg, clnt);
			gettimeofday(&stop, NULL);
			printf("Time elapsed (microSec): %lu\n", stop.tv_usec - start.tv_usec);

			printf("\nSERVER RESPONSE > Sorted array: ");
			for (i = 0; i < get_sort_1_arg.len; i++)
			{
				data[i] = result_2->element[i];
				printf("%d ", data[i]);
			}
			printf("\n");

			if (result_2 == (sortElement *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
		}

		/*
                *If this condition is true then it will send a message to server
                *message will be user given input
		*Server will reply the same message to client again
                */		
		else if (choice == 'e')
		{
			char string[100], c;
			int i;
			printf("Provide echo msg: ");
			scanf("%s", string);
			i = strlen(string); 		// length of user input till first space
			do{
				scanf("%c", &c);
				string[i++] = c;	// reading characters after first space (including it)
			} while (c != '\n'); 		// until user hits Enter
			
			string[i - 1] = 0;

			get_echo_1_arg = string;
			
			struct timeval stop, start;
			gettimeofday(&start, NULL);
			result_3 = get_echo_1(&get_echo_1_arg, clnt);
			gettimeofday(&stop, NULL);
			printf("Time elapsed (microSec): %lu\n", stop.tv_usec - start.tv_usec);

			printf("\nSERVER RESPONSE > Echo msg: %s\n", *result_3);

			if (result_3 == (char **)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
		}

		/*
                *If this condition is true then it will pass a file name to server
                *File name will be user given input
		*Server will reply based on the file status (exists or not)
                */
		else if (choice == 'c')
		{
			printf("Provide file name: ");
			scanf("%s", get_check_1_arg);

			struct timeval stop, start;
			gettimeofday(&start, NULL);
			result_4 = get_check_1(&get_check_1_arg, clnt);
			gettimeofday(&stop, NULL);
			printf("Time elapsed (microSec): %lu\n", stop.tv_usec - start.tv_usec);

			printf("\nSERVER RESPONSE > %s\n", *result_4);

			if (result_4 == (char **)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
		}

		/*
                *If this condition is true then it will pass two matrices to server
                *Both input matrices value will be user given inputs
		*In return server will reply the multiplicattion value of given matrices
                */
		else if (choice == 'm')
		{
			int r1, c1, c2, j=0, k=0, i;
			printf("Provide 1st Matrix Row and Column value: ");
			scanf("%d %d", &r1, &c1);
			get_matmul_1_arg.r1 = r1;
			get_matmul_1_arg.c1 = c1;
			printf("\n1st Matrix Elements: \n");
			for (i = 0; i < r1*c1; i++){
					printf("matA[%d][%d] = ", j, k);
					scanf("%d", &get_matmul_1_arg.matA[i]);
					
					if(k == c1 - 1){
						k=0;
						j++;
					}
					else{
						k++;
					}
					printf("\n");
			}

			j = 0;
			k =  0;
			printf("\nProvide 2nd Matrix Column value: ");
			scanf("%d", &c2);
			get_matmul_1_arg.c2 = c2;
			printf("\n2nd Matrix Elements: \n");
			for (i = 0; i < c1*c2; i++){
				printf("matB[%d][%d] = ", j, k);
				scanf("%d", &get_matmul_1_arg.matB[i]);
				
				if(k == c2 - 1){
						k=0;
						j++;
					}
					else{
						k++;
					}
					printf("\n");
			}

			struct timeval stop, start;
			gettimeofday(&start, NULL);
			result_5 = get_matmul_1(&get_matmul_1_arg, clnt);
			gettimeofday(&stop, NULL);
			printf("Time elapsed (microSec): %lu\n", stop.tv_usec - start.tv_usec);

			int matC[100];
			printf("\nResulted Matrix: \n");
			for(i = 0; i< r1 * c2; i++){
				matC[i] = result_5->matC[i];
				if (i == c2)
					printf("\n");
				printf("%d\t", matC[i]);
			}
			printf("\n");

			if (result_5 == (matrixMulElements *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}

		/*For any other character input by user will terminate the loop*/
		else
		{
			printf("Closing Connection ...\n");
			break;
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_prog_1 (host);
exit (0);
}


