/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_matrixMulElements (XDR *xdrs, matrixMulElements *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (3 +  100  + 100  + 100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->r1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c1))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->matA, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c2))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->matB, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->matC, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->r1);
			IXDR_PUT_LONG(buf, objp->c1);
			{
				register int *genp;

				for (i = 0, genp = objp->matA;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->c2);
			{
				register int *genp;

				for (i = 0, genp = objp->matB;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->matC;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (3 +  100  + 100  + 100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->r1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c1))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->matA, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c2))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->matB, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->matC, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->r1 = IXDR_GET_LONG(buf);
			objp->c1 = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->matA;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->c2 = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->matB;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->matC;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->r1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c1))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->matA, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->matB, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->matC, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sortElement (XDR *xdrs, sortElement *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  1000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->element, 1000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->len))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->element;
					i < 1000; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->len);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  1000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->element, 1000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->len))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->element;
					i < 1000; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->len = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->element, 1000,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}
